apiVersion: 1

datasources:
  - name: TimescaleDB
    uid: timescaledb
    type: postgres
    access: proxy
    orgId: 1
    url: timescaledb:5432
    user: ${TSDB_POSTGRES_USER}
    secureJsonData:
      password: ${TSDB_POSTGRES_PASSWORD}
    jsonData:
      database: ${TSDB_POSTGRES_DB}
      sslmode: disable
      postgresVersion: 1400
      timescaledb: true
    isDefault: true
    editable: true